### ISSUE TITLE
Sort by due date doesn't sort

### ISSUE THREAD

**Issue by np-trivial** [davraamides/todotxt-mode#10]
When sorting by due date, all the items with a due: tag rise to the top, but they are not in any order than I can detect.

**Comment by davraamides** [comment]
Thanks. It looks like there is a bug with parsing the date part of the tag value. I will try and fix this and one or two other issues over the holiday and push an update. 

> On Nov 26, 2019, at 9:42 AM, np-trivial <notifications@github.com> wrote:
> 

﻿
When sorting by due date, all the items with a due: tag rise to the top, but they are not in any order than I can detect.

**Comment by davraamides** [comment]
Fixed with new release 1.4.10. Turns out the regex was wrong - it was only parsing the year part of `yyyy-mm-dd` so it sorted only on year. The use of `\w+` in the regex didn't match the `-` in the date.
