### ISSUE TITLE
'move tasks to Someday file' moves tasks to incubate.txt instead

### ISSUE THREAD

**Issue by alexbarten** [davraamides/todotxt-mode#13]
Hi,

I am using your extension all the time, and I like it a lot.

I just discovered a weird behavior though. I created a `someday.txt` file in the same folder as `todo.txt`, and selected the _move tasks to Someday file_ command to move a task. Instead of moving it to `someday.txt`, it created a new file named `incubate.txt`. And moved the task therein.

I cloned your code and looked into it. Could it be that there is an inconsistency in `todotxt-mode/src/settings.ts`? It assigns like this:
`export const SomedayFilename:string = 'incubate.txt'`

You only refer to incubate.txt in your notes.md, so I assume this is unintended. It did not help to change the someday.txt variable assignment in the VSCode extension settings, and neither did a restart of the editor have any effect (to change the assignment of the filename variable). 

Am I right, and if so, could you please adapt it?

Thanks in advance and kind regards (and keep up your great work!),

Alex

**Comment by davraamides** [comment]
That's a bug. I use the convention of `incubate.txt` instead of `someday.txt` and didn't notice it. And I have that setting hardwared in settings.ts rather than pulling from the User Preferences. I will push a fix soon.

**Comment by davraamides** [comment]
Fixed with 1.4.13, however a restart of the extension (or Code) is required after changing the name of file.

**Comment by alexbarten** [comment]
Thanks a lot for your fix! I tested it and it works.

Kind regards,
Alex
