### ISSUE TITLE
There's no license file

### ISSUE THREAD

**Issue by buenalabs** [davraamides/todotxt-mode#14]
Awesome work!

Though, there doesn't seem to be a license file for this project. Is this deliberate? Or is there a plan to add one in the future?

**Comment by davraamides** [comment]
Thanks, and let me check. I thought I had one!

> On Mar 21, 2020, at 8:30 AM, Ariel David Buena <notifications@github.com> wrote:
> 

﻿
Awesome work!

Though, there doesn't seem to be a license file for this project. Is this deliberate? Or is there a plan to add one in the future?

**Comment by davraamides** [comment]
Added a `LICENSE` file using the MIT License in the 1.4.15 release.
