### ISSUE TITLE
Publish to Open-VSX Marketplace for VSCodium

### ISSUE THREAD

**Issue by scandey** [davraamides/todotxt-mode#19]
Would you be willing to publish this extension to the Open-VSX Marketplace in addition to the Microsoft Marketplace?
For users avoiding the Microsoft telemetry in VSCode, many extensions are unavailable and I would love to be able to use your Todo.txt extension in my coding work.
For more info, theres a post by the group running open-vsx at [https://www.gitpod.io/blog/open-vsx/](https://www.gitpod.io/blog/open-vsx/).
Thanks for your consideration!

**Comment by davraamides** [comment]
Sure. I'll try and do it later this week.

**Comment by davraamides** [comment]
I published this today. It's listed here now: https://open-vsx.org/extension/davraamides/todotxt-mode
