### ISSUE TITLE
"Open note" link not properly rendered

### ISSUE THREAD

**Issue by xgid** [davraamides/todotxt-mode#2]
Hi there!

First of all, I want to be the first to give you my congratulations for this great extension! It works great, and the enhancements to the Todo.txt like the "note" metadata tag idea are fantastic. I use it all the time!

I want to report that there's a minor bug in the "note" metadata tag preview which makes the "Open note" markdown link to be shown in raw mode instead of rendered as an hyperlink:

![imagen](https://user-images.githubusercontent.com/12764559/62420080-304ed100-b663-11e9-862f-bf6f9b1ca9ae.png)

It's interesting to note that the contents of the note itself (the .md file) is being properly rendered. It's just the "Open note" link that it's not.

That being said, I think that it would even be better if the "note" metadata tag itself in the `todo.txt` file was converted to an hyperlink to the note, so clicking (or ctrl-clicking) it took you to the note file. Is that even possible? Should I open another issue for that enhancement?

## Version

I'm using version 1.4.5 of the extension.

**Comment by davraamides** [comment]
@xgid What OS are you on? I've been using this extension on macOS and Windows 10 and it renders correctly:

![image](https://user-images.githubusercontent.com/1895577/62465280-82275200-b75c-11e9-87da-ae022c62e724.png)

I will look into showing the note tag as a hyperlink. I'm pretty sure there is a way to do that.

**Comment by xgid** [comment]
I'm on Windows 10 Pro, v. 1809, 17763.615. 

May it be due to some other extension or VSCode configuration interfering? How could I check?

**Comment by davraamides** [comment]
Can you send me a sample note that is not working so I can debug it? Maybe
there is something in the note itself that's causing the Markdown to choke.
You can strip out anything sensitive.

**Comment by xgid** [comment]
I don't think that it has to do with the note contents, because I have the bug shown with all my notes, but anyway... here you are (with the `.txt` extension added to bypass GitHub upload file restrictions):

[ZTD-Note-20190801-165412.md.txt](https://github.com/davraamides/todotxt-mode/files/3468502/ZTD-Note-20190801-165412.md.txt)

**Comment by xgid** [comment]
@davraamides I would like to debug the problem at my side so I can help fixing it. Do you know how could I do that? I've programmed in Javascript in the past, but have no experience with the VSCode dev environment.

**Comment by davraamides** [comment]
I would go through this intro tutorial on VS Code Extension development to
get an overview and also to install the necessary tools and libraries:
https://code.visualstudio.com/api/get-started/your-first-extension

Once you have that, you can just clone my project from GitHub:
https://github.com/davraamides/todotxt-mode

Then you should be able to just run my extension in the debugger.

I didn't know VS Code or Typescript before I wrote this extension but I
found coming from JavaScript was pretty straightforward.

**Comment by xgid** [comment]
Great! Thanks for the tips. 

I could successfully debug the extension and found the bug: it is due to the filenames of the notes .md files not being URL encoded here:

https://github.com/davraamides/todotxt-mode/blob/6efb6462c7e4c25bde8b6b3c4238d210be09c871/src/extension.ts#L42

When you build the vscode.MarkdownString you should URL-encode `notePath` , including changing all the `\` to `/`. 

Oh, and on Windows the `file://` prefix should officially be `file:///`, though `file://` maybe also works... I'm not sure.

HTH!

**Comment by davraamides** [comment]
Ah, thanks! I will make the change. BTW, I added a fix yesterday where someone else reported the file:/// issue on Windows. Version 1.4.6 has that change and I’ve tested on Windows and macOS. 

On Aug 6, 2019, at 4:42 AM, Xavier G. Domingo <notifications@github.com> wrote:

Great! Thanks for the tips.

I could successfully debug the extension and found the bug: it is due to the filenames of the notes .md files not being URL encoded here:

https://github.com/davraamides/todotxt-mode/blob/6efb6462c7e4c25bde8b6b3c4238d210be09c871/src/extension.ts#L42

When you build the vscode.MarkdownString you should URL-encode notePath , including changing all the \ to /.

Oh, and on Windows the file:// prefix should officially be file:///, though file:// maybe also works... I'm not sure.

HTH!

**Comment by davraamides** [comment]
I've fixed the issue and released in 1.4.7. I do think there are some edge cases to consider between the note file name/path in the actual todo.txt file and the actual file system path, but I believe this addresses the issue as reported.

**Comment by xgid** [comment]
@davraamides Thanks for a so fast fix. Tested with 1.4.7 and it works great!

May I open another issue for my enhancement request of converting the whole "note" metadata tag into an hyperlink to the note?

**Comment by davraamides** [comment]
Sure. I will look into that when I can cut out some time. 

On Aug 6, 2019, at 2:42 PM, Xavier G. Domingo <notifications@github.com> wrote:

@davraamides Thanks for a so fast fix. Tested with 1.4.7 and it works great!

May I open another issue for my enhancement request of converting the whole "note" metadata tag into an hyperlink to the note?
