### ISSUE TITLE
Move tasks to done file is missing

### ISSUE THREAD

**Issue by buckleyGI** [davraamides/todotxt-mode#21]
Maybe this is a bug or maybe I don't understand.

Shouldn't there be a "Move tasks to done file"? here

![image](https://user-images.githubusercontent.com/2102864/98252345-198bde00-1f7a-11eb-97e4-7fc736e67aeb.png)

Thank you

**Comment by filviu** [comment]
It is called "Archive completed tasks"

![image](https://user-images.githubusercontent.com/2470335/98349370-92df0b80-2022-11eb-94e5-3313c591fb6b.png)

**Comment by buckleyGI** [comment]
Ah, I was on the wrong foot presuming the actions all started the same.

**Comment by davraamides** [comment]
Yes, I think of archiving as a more specific action then just moving a task to one of the other task files, but I can see how it may have been a little confusing.
