### ISSUE TITLE
Open VSX Listing: Signing the Publisher Agreement

### ISSUE THREAD

**Issue by brianking** [davraamides/todotxt-mode#22]
Thank you for being part of the Open VSX community by adding your extensions to the Open VSX Registry. Please note that the service was recently transferred to the Eclipse Foundation and urgent action on your part is needed so we can continue to list your extensions. To ensure uninterrupted service, please sign the Eclipse Publisher Agreement on or before January 8, 2021. If not signed by that date, your extensions will be delisted and will no longer appear on the site nor be available via the API. If you sign at a later date, your extensions will then be re-activated. The signing process is explained in the Wiki (steps 1 and 2).

Please also note that all extensions MUST have a license in order to be listed.

More details are in these recent blog posts:
https://blogs.eclipse.org/post/brian-king/open-vsx-registry-under-new-management
https://blogs.eclipse.org/post/brian-king/new-era-open-vsx-registry

If you are the project maintainer, we urge you to claim the namespace for your extension(s). To find out how to do this, see:
https://github.com/eclipse/openvsx/wiki/Namespace-Access

Today, there’s growing momentum around open source tools and technologies that support Visual Studio (VS) Code extensions. Leading global organizations are adopting these tools and technologies. This momentum has spurred demand for a marketplace without restrictions and limitations. Thanks for joining us on this journey as we continue to build the Open VSX community. We look forward to continued innovation from you in 2021!

**Comment by davraamides** [comment]
Hi Brian,

I read the agreement and agree to it, but did not see a method to actually
sign it. I also submitted an issue to claim the namespace "davraamides".

Let me know if there is anything else I need to do.
-David

**Comment by brianking** [comment]
Hi David, once you sign in with Github you can go to Settings where you will see an option to sign in to an Eclipse Account. During that process you can sign the publishers agreement.

**Comment by davraamides** [comment]
Ok. Thanks. 

On Jan 7, 2021, at 11:02 AM, Brian King <notifications@github.com> wrote:

﻿
Hi David, once you sign in with Github you can go to Settings where you will see an option to sign in to an Eclipse Account. During that process you can sign the publishers agreement.

**Comment by davraamides** [comment]
Sorry if I'm being dense, but when I log into my Github account and go to
Settings, I do not see any option to sign into an Eclipse account. I've
tried every one of the settings submenus in the left pane and cannot find
anything related to Eclipse.

**Comment by davraamides** [comment]
I had to create an account on eclipse.org to get to the contributor
agreement. I have now approved it but when I try and publish an update to
my extensions, I get the error:

❌  You must log in with an Eclipse Foundation account and sign a Publisher
Agreement before publishing any extension.

See the documentation for more information:

https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by spoenemann** [comment]
Hi @davraamides! Sorry for the confusion. It seems you signed the "Eclipse Contributor Agreement", which is for contributing code to open source projects hosted by the Eclipse Foundation (e.g. [openvsx](https://github.com/eclipse/openvsx)). The Publisher Agreement needed for publishing extensions to open-vsx.org is a different agreement. Please follow step 2 in the publishing guide to sign that agreement:
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by brianking** [comment]
According to https://github.com/EclipseFdn/open-vsx.org/issues/293#issuecomment-756711484, this looks resolved. Feel free to reopen if not.
