### ISSUE TITLE
cant redo in python, cpp or source files

### ISSUE THREAD

**Issue by tyoc213** [davraamides/todotxt-mode#23]
It seems that the shortcut `ctrl+shift+z` is always active, doesnt matter if inside or not from a todo.txt, pending.txt or any of the other files, it thinks all files, even .py and other source files as `todo files`.

**Comment by davraamides** [comment]
You should be able to restrict this with a "when" clause in the User
keybindings.json file like below. But you'll need to delete the Default
binding first or it will still be in effect. I'm not aware of a way  to do
this in general to match the todotxtmode.todoFilename setting since you'd
need to reference a variable.

{
"key": "ctrl+shift+z",
"command": "extension.decrementPriority",
"when": "resourceFilename == 'todo.txt'"
}

**Comment by tyoc213** [comment]
From where I can open this file?

![image](https://user-images.githubusercontent.com/506234/104053971-cf112280-51b1-11eb-92d9-3d32d0108d8e.png)

**Comment by davraamides** [comment]
You can open it with:
View->Open Command Pallette and then select "Preferences: Open Keyboard
Shortcuts (JSON)"

**Comment by tyoc213** [comment]
Found it in the default json

![image](https://user-images.githubusercontent.com/506234/104112065-c69f1180-52af-11eb-95ce-eef1f259824d.png)


But could only edit from `File->preferences->Keyboard short cuts` or `Ctrl+k Ctrl+s`

![image](https://user-images.githubusercontent.com/506234/104112096-31504d00-52b0-11eb-8849-a10a96ca350a.png)


You need to right click then "edit when"

Here is my current expression `resourceFilename == 'done.txt' || resourceFilename == 'someday.txt' || resourceFilename == 'todo.txt' || resourceFilename == 'waiting.txt'`

**Comment by sjwo** [comment]
I've tried to follow the suggestion above, but the todotxt-mode extension Ctrl-Shift-Z keybinding is still active outside of the specified files.

Here is what my  `~/.config/Code/User/keybindings.json` looks like:

```
// Place your key bindings in this file to override the defaults
[
    {
        "key": "ctrl+shift+z",
        "command": "extension.decrementPriority",
        "when": "resourceFilename == 'done.txt' || resourceFilename == 'someday.txt' || resourceFilename == 'todo.txt' || resourceFilename == 'waiting.txt'"
    }
]
```
I've tried reloading the window.

**Comment by davraamides** [comment]
There is probably a default binding that is still in effect. Go to Code -> Preferences -> Keyboard Shortcuts and filter for "priority". If you see bindings with Source "Extension" that are conflicting, right-click and select Remove Keybinding, leaving just the User binding with the "when" clause.

**Comment by sjwo** [comment]
That did the trick! Thank you!

For reference, I'm attaching before and after screenshots.

# Before
![image](https://user-images.githubusercontent.com/44107090/146200694-94fc91b5-2e18-4d15-ba08-8553ed98e175.png)
# After
![image](https://user-images.githubusercontent.com/44107090/146200988-538561c6-3722-47fe-95bd-5c4f975c61dc.png)
# Thoughts
- It seems odd that the Source: User keybindings don't override the Source: Extension
keybindings.
- Maybe making the When values for the Source: Extension keybindings' default to `resourceFilename == 'done.txt' || resourceFilename == 'someday.txt' || resourceFilename == 'todo.txt' || resourceFilename == 'waiting.txt` would be more intuitive for new users going forward?

**Comment by davraamides** [comment]
I agree that it's a bit backwards that the user settings don't override the global ones. I'm going to look into defining the shortcuts in the extension so they include the "when" clause but it's tricky since people can change the default names of the various todo files.

**Comment by o-alquimista** [comment]
Using a regular expression to [match](https://code.visualstudio.com/api/references/when-clause-contexts#match-operator) all files that end in `todo.txt`:

```json
[
    {
        "key": "ctrl+shift+z",
        "command": "extension.decrementPriority",
        "when": "editorTextFocus && resourceFilename =~ /todo.txt$/"
    },
    {
        "key": "ctrl+shift+z",
        "command": "-extension.decrementPriority",
        "when": "editorTextFocus"
    }
]
```

@davraamides What do you think? I believe this could become the default.
