### ISSUE TITLE
Syntax highlighting missing for other files

### ISSUE THREAD

**Issue by metbril** [davraamides/todotxt-mode#24]
The only file that gets highlighted is `todo.txt` itself. Any other file (done, someday) is just plain text.

Workspace setting:

```json
{
    "todotxtmode.excludeDecorationsFilePattern": "",
    "todotxtmode.todoFilePattern": "^.*\\.txt$"
}
```

**Comment by davraamides** [comment]
Hi Robert,

I think the excludeDecorationsFilePattern is matching anything (it's a
regex). Try changing it to "^$" which will only match the empty string
(i.e. won't match any file name). You may need to restart VSC for the
effect to take place.

-David

**Comment by metbril** [comment]
Hi. I changed the regex to your suggestion "^$" and restarted VSC. That did the trick. Thanks.
