### ISSUE TITLE
Make the note filename pattern customizable

### ISSUE THREAD

**Issue by phybros** [davraamides/todotxt-mode#25]
Right now using the `Create note for task` command will make a file called `[Task]-Note-20210210-143437.md` where the `[Task]` part is highlighted.

I'd love to be able to have the date/timestamp first and the `[Task]` second.

**Comment by phybros** [comment]
I see it's hardcoded at https://github.com/davraamides/todotxt-mode/blob/master/src/note.ts#L34 maybe we could make a new setting which lets you do a pattern e.g. the default would be `\[Task\]-Note-%d-%t.md` or something along those lines. Then make `valueSelection` just the range between the square brackets (if there are any in the pattern)?

**Comment by davraamides** [comment]
That's a good suggestion and seems pretty straightforward to implement. I will try and knock it out soon.

**Comment by davraamides** [comment]
Fixed with 1.4.20. See the [change log](https://marketplace.visualstudio.com/items/davraamides.todotxt-mode/changelog) for details.

**Comment by phybros** [comment]
Nice! This is perfect. One nitpick though, the changelog says `[Task]` but the default setting uses `[Todo]`

**Comment by davraamides** [comment]
Shoot - my bad. I'll fix the changelog.
