### ISSUE TITLE
support [ ] and [x]

### ISSUE THREAD

**Issue by hukadev** [davraamides/todotxt-mode#26]
Hello,

Could you consider support [ ] and [x] prefix for each task?
Example:

- [ ] todo is not done
- [x] done

Best regards,
Huka

**Comment by davraamides** [comment]
Hi Huka,

I've tried to stay true to the [todo.txt spec](https://github.com/todotxt/todo.txt) as much as possible so that the text files themselves are compatible with other tools that follow that convention. Using []'s would break that.

**Comment by hukadev** [comment]
Hi @davraamides 

I got it.
Thanks.
