### ISSUE TITLE
feature request: auto-insert note references

### ISSUE THREAD

**Issue by np-trivial** [davraamides/todotxt-mode#27]
Feature request: when using "Create note for task" feature, replace the selected text with the reference to the note, rather than just putting the reference in the clipboard. 

I've never done anything other than immediately paste that link into the todo.txt file. Seems like it should just happen automatically so that I don't accidentally lose the clipboard text.

**Comment by davraamides** [comment]
I added a `replaceNoteTextWithNoteTag` setting that will enable this behavior if set to `true` in your VS Code todotxt-mode extension settings. It's off by default. Available in v1.4.21.
