### ISSUE TITLE
Unable to open 'file': File is a directory.

### ISSUE THREAD

**Issue by jdckr** [davraamides/todotxt-mode#3]
Hi,
great addon. I like the ability to add notes to my tasks. But when trying to open a note I get the following error:
![grafik](https://user-images.githubusercontent.com/40456550/62441203-7f742f00-b753-11e9-9e98-66938f8859f5.png)
I assume the issue is that the file link ends with a "/". You can see it when hovering over **open**.

**Comment by jdckr** [comment]
I patched the code to use `file:///` instead of `file://`.

**Comment by davraamides** [comment]
@jdckr Thanks for pointing this out. I will make the change. BTW, what OS are you on? I know historically the "file:" protocol for opening files from links can be OS/browser-specific but hopefully VS Code behaves consistently regardless of the OS.

**Comment by davraamides** [comment]
Fixed with 1.4.6. Tested on Windows 10 and macOS Mojave (VS Code 1.36.1)

**Comment by jdckr** [comment]
> 
> 
> @jdckr Thanks for pointing this out. I will make the change. BTW, what OS are you on? I know historically the "file:" protocol for opening files from links can be OS/browser-specific but hopefully VS Code behaves consistently regardless of the OS.

I am on Windows 10.

**Comment by davraamides** [comment]
I pushed a fix. It turns out that you need file:/// for Windows and file://
for macOS. Not sure about Linux as I haven't tried it. Install 1.4.6 and
see if that works for you.
