### ISSUE TITLE
"Increment/Decrement priority of selected tasks" apply for selected tasks

### ISSUE THREAD

**Issue by hukadev** [davraamides/todotxt-mode#30]
Hello,

I tried to select multiple tasks (highlighted) then run "Increment/Decrement priority of selected tasks" but it only affect to the first one.
Could you consider support to apply all selected tasks?
I'm using version v1.4.21

Best regards,
Huka

**Comment by davraamides** [comment]
Thanks. It looks like there may have been a change to the VS Code Extension API that broke the way I was doing multi-line edits. It also impacted the `toggleCompletion` command. I fixed this in v1.4.24.

**Comment by hukadev** [comment]
Hi @davraamides 

I tested it, it works.
Thank you for your time and effort.

**Comment by hukadev** [comment]
Hi @davraamides 

I found an issue that if I run "Increment/Decrement priority of selected tasks", I lose the selection, which means I have to select multiple tasks again to change their priority.

Could you please consider it?

**Comment by davraamides** [comment]
I fixed this along with other multi-line commands, to restore the selection after the edit.
