### ISSUE TITLE
Feature Request - Extension Setting to Change Date Format

### ISSUE THREAD

**Issue by cldjr1** [davraamides/todotxt-mode#33]
Any chance you could add an Extension Setting to allow changes to the due-date format? Or expand the date-recognition to allow variations of the date formatting? 
For example, I prefer MM/DD/YYYY.

**Comment by davraamides** [comment]
It shouldn't be too difficult to pull that regex pattern into a setting. I'll put it on my queue.

**Comment by davraamides** [comment]
I finally got around to doing this. There is a new `tagDatePattern` setting where you can specify a `strftime`-style format string, such as "%m/%d/%Y". It's in version 1.4.28.
