### ISSUE TITLE
Projects, contexts and tags in russian do not work.

### ISSUE THREAD

**Issue by Yersh** [davraamides/todotxt-mode#37]
![todotxt-mode_highlight_problems___](https://user-images.githubusercontent.com/25032047/126827118-02fc53e8-c7a7-48f1-b2bf-f3bcd2225f47.png)

If you write projects, contexts and tags in russian, they are not highlighted correctly.
To my understanding they are not treated as keywords at all, since sorting operations (like todotxt-mode: Sort by Context) do not work on them.

**Comment by davraamides** [comment]
Hi Yersh - can you verify that you are on version 1.4.25? I released a version for this [pull request](https://github.com/davraamides/todotxt-mode/pull/31) which I believe fixed it. Here's an image of a quick test I tried on my machine:

<img width="451" alt="Screen Shot 2021-07-23 at 3 00 46 PM" src="https://user-images.githubusercontent.com/1895577/126829122-d871445d-4f4b-4143-80aa-04c0d8f015ba.png">

**Comment by Yersh** [comment]
ok, my bad. I was on 1.4.24. 
update fixed the problem. 
thanks for the quick answer,
and thanks for the great extension.

**Comment by davraamides** [comment]
It may have been my bad! (If you are getting your extension from Open VSX rather than VS Marketplace). Last time I did a release I only pushed it to the VS Marketplace and forgot to push to Open VSX. I just fixed that a minute ago.
