### ISSUE TITLE
Make the "note" metadata tag an hyperlink

### ISSUE THREAD

**Issue by xgid** [davraamides/todotxt-mode#4]
It would be great if the "note" metadata tag in the `todo.txt` file was converted to an hyperlink to the note, so ctrl-clicking it took you to the note file.

**Comment by davraamides** [comment]
Sorry - this has been implemented for a long time in a different way and I overlooked it. If you have a note tag such as `note:comments.txt` then when you hover over the tag, a preview of the contents of `comments.txt` will be display with a link to click on to open the text file.
