### ISSUE TITLE
Exclude images dir from .vscodeignore

### ISSUE THREAD

**Issue by Crystal-RainSlide** [davraamides/todotxt-mode#41]
Currently, the .vsix package includes the "images" dir, and the size of it is about 30+MB.
One may go to https://marketplace.visualstudio.com/items?itemName=davraamides.todotxt-mode and click "Download Extension" to see the size of it.

To trim down the size of the .vsix package, please add `images/**` to the .vscodeignore file.

I'm not a VSCode extension developer, please currect me if it's not the right way to do so~

**Comment by Crystal-RainSlide** [comment]
And https://github.com/davraamides/todotxt-mode/blob/c323cdacb73a2c74110268c4f002fde79789de91/images/.DS_Store

As `.DS_Store` is already in .gitignore, you may need to ignore, or delete it from this repo, manually.

Also see: https://github.com/github/gitignore

**Comment by davraamides** [comment]
Thanks. Clearly, I'm not much of a VSCode extension developer, either! 

I excluded the images and republished the extension as 1.4.29. It's no 2.3M vs 40M.
