### ISSUE TITLE
Extension is hard to find 

### ISSUE THREAD

**Issue by filviu** [davraamides/todotxt-mode#5]
When searching for the (to me) obvious term todo.txt in the VSCode extensions list this (obviously superior, thank you !) extension cannot be found. I found it by mistake typing todotxt.

Thanks for your work !

**Comment by davraamides** [comment]
That's really strange. Note from the extension home page, I use "todo.txt" four times.

![image](https://user-images.githubusercontent.com/1895577/64290242-b8124e80-cf33-11e9-8154-9aea9d229ea2.png)

**Comment by davraamides** [comment]
Whatever the issue was, I can find it now by searching for "todo.txt", although it's not very high on the result list. Closing this issue.

**Comment by filviu** [comment]
You are right I can find it but it is but way down. I guess it promotes results based on title than content. Anyways thanks for your extension, I like it a lot !
