### ISSUE TITLE
Open VSX - extension outdated, update possible ?

### ISSUE THREAD

**Issue by Gofannon** [davraamides/todotxt-mode#57]
Hello,

Extension version on [open VSX](https://open-vsx.org/extension/davraamides/todotxt-mode) is 1.4.25 while being [1.4.32 - 2023-04-21](https://github.com/davraamides/todotxt-mode/blob/master/CHANGELOG.md#1432---2023-04-21) in the changelog

Could you update it? Or, is there any issue preventing it ?

Thanks for your work.

### Related issues

https://github.com/davraamides/todotxt-mode/issues/22
https://github.com/davraamides/todotxt-mode/issues/19

**Comment by davraamides** [comment]
@Gofannon I just published it. I remember I was getting errors publishing to Open VSX last time I made a change and I never revisited it.
