### ISSUE TITLE
Task completion format is wrong when used with priority

### ISSUE THREAD

**Issue by mheden** [davraamides/todotxt-mode#6]
The resulting format when completing a task seem to be wrong when using a priority.

Example:
`(A) Foo Bar @project` becomes `x 2019-09-26 (A) Foo Bar @project`

According to the specification (https://github.com/todotxt/todo.txt/blob/master/description.png) the result should be `x (A) 2019-09-26 Foo Bar @project` or `x 2019-09-26 Foo Bar @project` (priority could apparently be dropped).

**Comment by davraamides** [comment]
Good catch. I hadn't noticed that. I'll have to rework the completion logic a bit since I'm simply prepending/deleting the first 13 characters right now, which won't work.

**Comment by davraamides** [comment]
Fixed with new release of 1.4.10.
