### ISSUE TITLE
Popup of Markdown notes seem to show the note 4 times within the popup

### ISSUE THREAD

**Issue by klumpth** [davraamides/todotxt-mode#8]
In the image below we see the note 2 times (in sum it appears 4 times):

![image](https://user-images.githubusercontent.com/56550753/66758871-6e584480-ee9f-11e9-9a65-69226e956c31.png)

**Comment by davraamides** [comment]
Thanks. Can you post the Markdown text of the note?

**Comment by klumpth** [comment]
```
# Test Note

- list 1
- list 2

End of Note.
```

**Comment by klumpth** [comment]
[Test-Note-20191014-164449.zip](https://github.com/davraamides/todotxt-mode/files/3724948/Test-Note-20191014-164449.zip)

**Comment by klumpth** [comment]
I now installed your (very nice!) extension onto another PC - and there it worked! So maybe it remains, where it could fail to show up 4 previews. It seems to work in principal. Thanks.

**Comment by klumpth** [comment]
Now after a re-install of VSCode it works correctly. Sorry for any inconvenience!

**Comment by davraamides** [comment]
No worries. Glad that resolved it!
